mystr = "Hello, I'm Elliot"
print(mystr)
print(len(mystr))
print(mystr[0:])
print(mystr[:])
print(mystr[0:79])
print(mystr[0:5])
print(mystr[:5])
print(mystr[0:16:2])
print(mystr[::2])
print(mystr[-1])
print(mystr[-6:])
print(mystr[::-1])