import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("C://")
# print(os.getcwd())
# f = open("22_textfile")
# print(os.listdir("C://"))
# os.mkdir("This")
# os.makedirs("This/that")
# os.rename("harry.txt", "codewithme.txt")
# print(os.environ.get('Path'))
# print(os.path.join('C:/', '/elliot.txt'))
# print(os.path.exists("C://"))
print(os.path.isdir("C://pythonProject-rebeginnig"))
